name: import

on:
  push:
    branches:
      - docs-import

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v0
        with:
          service_account: github-actions@test1-395206.iam.gserviceaccount.com
          workload_identity_provider: projects/562436113365/locations/global/workloadIdentityPools/github-actions-1/providers/github01
      
      - uses: r7kamura/google-docs-to-github@v3
        with:
              google_drive_folder_id: 1oVMxR8FtWre1k2bqDOxpLYbPDUrifBv7  

      - name: Echo "success"
        run: echo "success"