name: import

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v0
        with:
          service_account: doc2github@doc2github.iam.gserviceaccount.com
          workload_identity_provider: projects/1004789866380/locations/global/workloadIdentityPools/githubaction/providers/my-provider-id
      
      - name: Check installation
        run: |
            echo "success!"