name: import

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v0
        with:
          service_account: github-actions@test1-395206.iam.gserviceaccount.com
          workload_identity_provider: projects/562436113365/locations/global/workloadIdentityPools/github-actions-1/providers/my-provider-id
      
      - name: Echo "success"
        run: echo "success"